### PR TITLE
Update README_zh-tw.md

### PR DESCRIPTION
**Pull request by Sea-n**

### CODE REVIEW

**Comment by birkhofflee** [comment]
Slightly changed your wording to respect the original author's meaning, please check

**Comment by Sea-n** [comment]
請問主要是指哪些部分修改的不好？
方便的話麻煩請指出是第幾行

**Comment by birkhofflee** [comment]
https://github.com/Sea-n/have-fun-with-machine-learning-zhtw/commit/0d6666b515f226dbffaec0e17fb99538cac5f500

**Comment by Sea-n** [comment]
[Line 70](https://github.com/Sea-n/have-fun-with-machine-learning-zhtw/commit/0d6666b515f226dbffaec0e17fb99538cac5f500#diff-321feddc3148cbcdc0b504f7f306b2ceL70) 原文如下

> In the end I found this one to be the closest.

我認為這是指文章內容的接近，並不是只時間的接近

**Comment by Sea-n** [comment]
[Line 706](https://github.com/Sea-n/have-fun-with-machine-learning-zhtw/commit/0d6666b515f226dbffaec0e17fb99538cac5f500#diff-321feddc3148cbcdc0b504f7f306b2ceL706) 我將「概率」改為「機率」
根據下列網頁顯示其為同義詞，但台灣主要以機率為主
[ref1](http://terms.naer.edu.tw/detail/974722/), [ref2](https://tw.answers.yahoo.com/question/index?qid=20120514000051KK00584)

**Comment by birkhofflee** [comment]
完整原文如下
> On a Mac it can be frustrating to get working, with version issues halting
your progress at various steps in the build.  It took me a couple of days
of trial and error.  There are a dozen guides I followed, each with slightly
different problems.  In the end I found [this one](https://gist.github.com/doctorpangloss/f8463bddce2a91b949639522ea1dcbe4) to be the closest.
I’d also recommend [this post](https://eddiesmo.wordpress.com/2016/12/20/how-to-set-up-caffe-environment-and-pycaffe-on-os-x-10-12-sierra/),
which is quite recent and links to many of the same discussions I saw. For readers of Chinese,
[BirkhoffLee](https://github.com/BirkhoffLee) has also suggested his
[complete guide](https://blog.birkhoff.me/macos-sierra-10-12-2-build-caffe) for how to build Caffe on macOS Sierra, written in Chinese.

你提到的那句 Markdown 原始碼如下
```
I’d also recommend [this post](https://eddiesmo.wordpress.com/2016/12/20/how-to-set-up-caffe-environment-and-pycaffe-on-os-x-10-12-sierra/), which is quite recent and links to many of the same discussions I saw.
```

其中 `which is quite recent` 是指時間的接近。

**Comment by Sea-n** [comment]
抱歉我誤解了，感謝大大糾正

**Pull request merged**
